"""add frames to profile avatar

Revision ID: 627c3ef5c466
Revises: c508476e7aaa
Create Date: 2025-11-05 12:01:20.260287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '627c3ef5c466'
down_revision: Union[str, Sequence[str], None] = 'c508476e7aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_frames_id'), 'profile_frames', ['id'], unique=False)
    op.create_table('user_frames',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('equipped', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['profile_frames.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_frames_id'), 'user_frames', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_frames_id'), table_name='user_frames')
    op.drop_table('user_frames')
    op.drop_index(op.f('ix_profile_frames_id'), table_name='profile_frames')
    op.drop_table('profile_frames')
    # ### end Alembic commands ###
