"""update email verification table

Revision ID: 95cf4cfec840
Revises: 3461f54ceacd
Create Date: 2025-11-01 22:46:15.403138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '95cf4cfec840'
down_revision: Union[str, Sequence[str], None] = '3461f54ceacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_verification_codes', sa.Column('email', sa.String(length=255), nullable=True))
    op.alter_column('email_verification_codes', 'code',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=6),
               nullable=True)
    op.alter_column('email_verification_codes', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.create_index(op.f('ix_email_verification_codes_id'), 'email_verification_codes', ['id'], unique=False)
    op.drop_column('email_verification_codes', 'new_email')
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_unique_constraint(None, 'teams', ['name'])
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False))
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.add_column('email_verification_codes', sa.Column('new_email', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_email_verification_codes_id'), table_name='email_verification_codes')
    op.alter_column('email_verification_codes', 'expires_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('email_verification_codes', 'code',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(length=10),
               nullable=False)
    op.drop_column('email_verification_codes', 'email')
    # ### end Alembic commands ###
