"""added tournament extra fields

Revision ID: c8a9173a8127
Revises: c279fea5bb67
Create Date: 2025-11-25 10:25:13.168917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c8a9173a8127'
down_revision: Union[str, Sequence[str], None] = 'c279fea5bb67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('format', sa.String(length=50), nullable=False))
    op.add_column('tournaments', sa.Column('team_count', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('status', sa.String(length=30), nullable=True))
    op.alter_column('user_badges', 'equipped',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_badges', 'equipped',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('tournaments', 'status')
    op.drop_column('tournaments', 'team_count')
    op.drop_column('tournaments', 'format')
    # ### end Alembic commands ###
