"""Add active_theme to users

Revision ID: dcfa655de613
Revises: 2bc44d0ba46d
Create Date: 2025-11-10 10:17:37.748639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcfa655de613'
down_revision: Union[str, Sequence[str], None] = '2bc44d0ba46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_theme', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'profile_themes', ['active_theme'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'active_theme')
    # ### end Alembic commands ###
