"""add equipped to user_inventory

Revision ID: f1919d1f31b4
Revises: dcfa655de613
Create Date: 2025-11-10 10:23:36.760373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1919d1f31b4'
down_revision: Union[str, Sequence[str], None] = 'dcfa655de613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_inventory', sa.Column('equipped', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_inventory', 'equipped')
    # ### end Alembic commands ###
